name: test

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  sast:
    name: Run SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run SAST
        run: semgrep ci
        env:
          SEMGREP_RULES: p/security-audit p/secrets p/owasp-top-ten